services:
  db:
    image: mariadb:10.6
    container_name: semaphore_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - semaphore_db_data:/var/lib/mysql
    restart: unless-stopped

  semaphore:
    build: .
    container_name: semaphore_ui
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SEMAPHORE_DB_HOST=db
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_USER=${MYSQL_USER}
      - SEMAPHORE_DB_PASS=${MYSQL_PASSWORD}
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=${MYSQL_DATABASE}
      - SEMAPHORE_PLAYBOOK_PATH=/ansible/
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
      - SEMAPHORE_ADMIN=${SEMAPHORE_ADMIN}
      - SEMAPHORE_ADMIN_PASSWORD=${SEMAPHORE_ADMIN_PASSWORD}
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - semaphore_config_data:/etc/semaphore
      - ./ansible:/ansible
    restart: unless-stopped

volumes:
  semaphore_db_data:
  semaphore_config_data: