- hosts: windows-desktops
  gather_facts: no
  tasks:
    - name: "Ping Windows Host"
      ansible.windows.win_ping:

    - name: "Check Windows Version"
      ansible.windows.win_shell: systeminfo | findstr /B /C:"OS Name"
      register: os_info

    - name: "Print OS Info"
      debug:
        msg: "{{ os_info.stdout }}"